server:
  port: 8080
  
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xyz
      username: root
      password: password
   liquibase:
      change-log: classpath:config/changelog/master.xml


   jpa:
     hibernate:
        ddl-auto: none
        generate-ddl: true

logging:
  level:
    liquibase: INFO